version: "3"
services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-data:/data   

  api:
    build:
        context: .
        dockerfile: Dockerfile.dev
    command: ["npm", "run", "start"]
    environment:
      PORT: 3000
      BROKER_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
        - rabbitmq
    ports:
        - 3000:3000
    volumes:
        - "./src:/app/src"
 
volumes:
  rabbit-data: